[package]
name = "modules"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
idna = "0.4.0"

bytes.workspace = true
futures.workspace = true
mozjs.workspace = true
paste.workspace = true
url.workspace = true
runtime.workspace = true

[dependencies.ion]
workspace = true
features = ["macros"]


[dependencies.tokio]
workspace = true
features = ["fs"]

[dependencies.tokio-stream]
version = "0.1.14"
features = ["fs"]

[dev-dependencies.tokio]
version = "1.33.0"
features = ["macros", "rt"]

[features]
debugmozjs = ["ion/debugmozjs"]

[lib]
test = false
doctest = false
