[workspace]
members = [
	"cli",
	"ion",
	"ion-proc",
	"modules",
	"runtime",
]
resolver = "2"

[workspace.dependencies]
colored = "2.0.4"
chrono = "0.4.31"
derivative = "2.2.0"
dunce = "1.0.4"
futures = "0.3.28"
indent = "0.1.1"
mozjs = { package = "mozjs", git = "https://github.com/wasmerio/mozjs", branch = "wasi" }
mozjs_sys = { package = "mozjs_sys", git = "https://github.com/wasmerio/mozjs", branch = "wasi" }
sourcemap = "6.4.1"
url = "2.4.1"

[workspace.dependencies.http]
version = "0.2.9"

[workspace.dependencies.hyper]
version = "0.14.27"
features = ["client", "http1", "tcp"]

[workspace.dependencies.hyper-rustls]
version = "0.24.1"
default-features = false
features = ["http1", "logging", "tls12", "webpki-tokio"]

[workspace.dependencies.tokio]
version = "1.24.2"
features = ["rt"]
