[package]
name = "runtime"
version = "0.1.0"

edition.workspace = true
license.workspace = true
authors = ["Redfire <redfire75369@hotmail.com>"]

[dependencies]
base64 = "0.21.7"
data-url = "0.3.1"
dirs = "5.0.1"
form_urlencoded = "1.2.1"
indexmap = "2.2.2"
sha3 = "0.10.8"
term-table = "1.3.2"
uri-url = "0.3.0"

bytes.workspace = true
chrono.workspace = true
dunce.workspace = true
encoding_rs.workspace = true
futures.workspace = true
indent.workspace = true
mozjs.workspace = true
paste.workspace = true
sourcemap.workspace = true
url.workspace = true
hyper-multipart-rfc7578 = "0.8.0"
as-any = "0.3.1"
multer = "3.0.0"

[dependencies.async-recursion]
version = "1.0.5"
optional = true

[dependencies.const_format]
version = "0.2.32"
optional = true

[dependencies.http]
version = "0.2.11"
optional = true

[dependencies.http-body-util]
version = "0.1.0"
optional = true

[dependencies.hyper]
version = "0.14.28"
features = ["client", "http1", "tcp"]
optional = true

[dependencies.rustls]
version = "0.22.2"
optional = true

[dependencies.hyper-rustls]
version = "0.25.0"
default-features = false
features = ["http1", "ring", "tls12", "webpki-tokio"]
optional = true

[dependencies.ion]
workspace = true
features = ["macros", "sourcemap"]

[dependencies.mime]
version = "0.3.17"
optional = true

[dependencies.pin-project]
version = "1.1.4"
optional = true

[dependencies.swc_core]
version = "0.90.6"
features = [
	"common",
	"common_sourcemap",
	"common_tty",
	"ecma_ast",
	"ecma_codegen",
	"ecma_parser",
	"ecma_transforms",
	"ecma_parser_typescript",
	"ecma_transforms_typescript",
	"ecma_visit",
]

[dependencies.sys-locale]
version = "0.3.1"
optional = true

[dependencies.tokio]
workspace = true
features = ["sync", "rt", "fs"]

[features]
debugmozjs = ["ion/debugmozjs"]
fetch = [
	"dep:async-recursion",
	"dep:const_format",
	"dep:http",
	"dep:http-body-util",
	"dep:hyper",
	"dep:rustls",
	"dep:hyper-rustls",
	"dep:mime",
	"dep:pin-project",
	"dep:sys-locale",
]

[lints]
workspace = true

[lib]
test = false
doctest = false
