[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
base64-url = "2.0.0"
closure = "0.3.0"
dirs = "5.0.1"
encoding_rs = "0.8.33"
form_urlencoded = "1.2.0"
indexmap = "2.0.2"
os_str_bytes = "6.5.1"
sha3 = "0.10.8"
term-table = "1.3.2"

chrono.workspace = true
derivative.workspace = true
dunce.workspace = true
futures.workspace = true
indent.workspace = true
mozjs.workspace = true
paste.workspace = true
sourcemap.workspace = true
url.workspace = true

[dependencies.bytes]
workspace = true
optional = true

[dependencies.http]
workspace = true
optional = true

[dependencies.hyper]
workspace = true
optional = true

[dependencies.hyper-rustls]
workspace = true
optional = true

[dependencies.ion]
path = "../ion"
features = ["macros", "sourcemap"]

[dependencies.swc_core]
version = "0.79.69"
features = ["common"]

[dependencies.swc_common]
version = "0.31.21"
features = ["sourcemap", "tty-emitter"]

[dependencies.swc_ecmascript]
version = "0.231.59"
features = ["codegen", "parser", "transforms", "typescript", "visit"]

[dependencies.tokio]
version = "1.24.2"
default-features = false
features = ["sync"]

[features]
debugmozjs = ["ion/debugmozjs"]
promise-logger = []
fetch = ["dep:bytes", "dep:http", "dep:hyper", "dep:hyper-rustls"]


[lib]
test = false
doctest = false
