[package]
name = "ion"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
bitflags = "1.3.2"
chrono = "0.4.19"
colored = "2.0.0"
derivative = "2.2.0"
futures = { version = "0.3.21", features = ["executor"] }
indent = "0.1.1"
ion-proc = { path = "../ion-proc" }
libffi = "3.0.0"
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
mozjs_sys = { package = "mozjs_sys", git = "https://github.com/servo/mozjs", rev = "4cd3f5b81f4c363c039631bf870e61a00c983f63" }

[features]
debugmozjs = ["mozjs/debugmozjs"]

[lib]
test = false
doctest = false

[[test]]
name = "array"
path = "./tests/objects/array.rs"
[[test]]
name = "date"
path = "./tests/objects/date.rs"
[[test]]
name = "object"
path = "./tests/objects/object.rs"

[[test]]
name = "string"
path = "./tests/primitives/string.rs"
