[package]
name = "ion-proc"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
convert_case = "0.6.0"
quote = "1.0.33"
prettyplease = "0.2.15"
proc-macro2 = "1.0.69"

[dependencies.syn]
version = "2.0.38"
features = ["extra-traits", "full", "visit-mut"]

[lib]
proc-macro = true
test = false
doctest = false
